# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ibnesayeed/setup-ipfs@master
        with:
          run_daemon: true
      - name: Pin Author Page
        shell: bash
        run: |
          set -o pipefail
          ipfs pin add QmNhnNDXE2wgPJbijE5Sgx651AJdy4b8jPs7nQezYYLAbE
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: yarn
      - run: yarn build
      - run: yarn test:unit
